---
#########################################
#################CentOS##################
#########################################
- name: restart webmin
  service: name=webmin state=restarted

- name: restart iptables
  service: name=iptables state=reloaded
#########################################
################Debian###################
#########################################
- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded
