---
  - name: Add repository (Webmin part-1 )
    apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present
  - name: Add repository (Webmin part-2)
    apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' state=present
  - name: Add GPG Key 
    apt_key: url=http://www.webmin.com/jcameron-key.asc state=present

  - name: Install webmin and dependencies
    apt: name={{ item }} state=present update_cache=yes
    with_items:
     - webmin
     - libnet-ssleay-perl
     - libnet-ssleay-perl
     - libauthen-pam-perl
     - libio-pty-perl
     - apt-show-versions
     - libapt-pkg-perl

  - name: configuration changes to webmin (webmin.acl)
    template: src=webmin.acl.php.j2 dest=/etc/webmin/webmin.acl backup=yes
    notify:
      - restart webmin

  - name: configuration changes to webmin (miniserv.users)
    template: src=miniserv.users.php.j2 dest=/etc/webmin/miniserv.users backup=yes
    notify:
      - restart webmin

  - name: insert ufw rule
    ufw: rule=allow port="{{ service_port_webmin }}" proto=tcp
  
  - name: start webmin service and enable to start at boot
    action: service name=webmin state=started enabled=yes
