---
  - include: centos.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    tags:
       - install-webmin

  - include: debian.yml
    when: ansible_os_family == "Debian"
    tags:
       - install-webmin
